"""
SYNTHETIC tests for the CIC-IDS2017 pipeline.

Every CSV here is generated by `_write_synthetic_csv`. The files only imitate the quirks of the real
MachineLearningCVE files (padded headers, a duplicated 'Fwd Header Length' column, 'Infinity' strings,
empty cells, U+FFFD in web-attack labels, missing files). Nothing in this module measures real
detection performance. Real benchmark results come only from `python -m src.run_cicids2017` on the
official CSVs, and are written with data_source = "real CIC-IDS2017 CSVs".
"""

import csv
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from sklearn.model_selection import train_test_split

from src.data.audit import audit_cicids2017
from src.data.dataset_adapters import CICIDS2017Adapter
from src.data.loaders import CICIDS2017_EXPECTED_FILES, CICIDS2017Loader, DatasetNotFoundError
from src.evaluation.detection_metrics import binary_detection_metrics, multiclass_metrics
from src.preprocessing.leakage import drop_identifier_columns, single_feature_leakage_scan
from src.preprocessing.pipeline import CyberthreatPreprocessingPipeline
from src.preprocessing.sampling import sample_positions
from src.run_cicids2017 import run_pipeline
from src.utils.config import load_config

SYNTHETIC_SOURCE = "synthetic test fixture"

# Same padding and duplicated-column quirks as the real CSV header.
SYNTHETIC_HEADER = [
    " Destination Port", " Flow Duration", " Total Fwd Packets", " Total Backward Packets",
    "Total Length of Fwd Packets", " Fwd Header Length", " Flow Packets/s", "Flow Bytes/s",
    " Flow IAT Max", " Flow IAT Min", " Fwd Header Length", " Label",
]
WEB_ATTACK = "Web Attack � Brute Force"  # U+FFFD, as stored in the real CSVs
LABELS = ["BENIGN", "DoS Hulk", "PortScan", WEB_ATTACK, "Heartbleed"]
LABEL_P = [0.6, 0.22, 0.12, 0.052, 0.008]


def _write_synthetic_csv(path: Path, n_rows: int, seed: int, rare_rows: int = 0) -> Path:
    """Writes one synthetic CSV with the real header quirks. Attack rows have heavier, shorter flows."""
    rng = np.random.default_rng(seed)
    labels = list(rng.choice(LABELS, size=n_rows, p=LABEL_P))
    labels[:rare_rows] = ["Heartbleed"] * rare_rows
    rows = []
    for label in labels:
        attack = label != "BENIGN"
        duration = 0 if rng.random() < 0.02 else float(rng.exponential(50 if attack else 1000))
        fwd = int(rng.poisson(40 if attack else 5))
        bwd = int(rng.poisson(2 if attack else 5))
        total_len = fwd * float(rng.uniform(40, 100))
        if duration == 0:
            rate_bytes, rate_pkts = "Infinity", "Infinity"
        else:
            rate_bytes = total_len / duration * 1e6
            rate_pkts = (fwd + bwd) / duration * 1e6
        iat_min = "" if rng.random() < 0.03 else duration * 0.1  # empty cell -> NaN
        rows.append([
            int(rng.choice([22, 80, 443, 8080])) if attack else int(rng.choice([80, 443])),
            duration, fwd, bwd, total_len, 20 * fwd, rate_pkts, rate_bytes,
            duration * 0.6, iat_min, 20 * fwd, label,  # second 'Fwd Header Length' copy is identical, as in the real data
        ])
    rows += rows[:5]  # exact duplicate rows
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(SYNTHETIC_HEADER)
        writer.writerows(rows)
    return path


@pytest.fixture
def synthetic_raw_dir(tmp_path):
    """Three of the eight expected files, so the loader must report the others as missing."""
    raw = tmp_path / "raw"
    raw.mkdir()
    _write_synthetic_csv(raw / CICIDS2017_EXPECTED_FILES[0], 400, seed=1)
    _write_synthetic_csv(raw / CICIDS2017_EXPECTED_FILES[2], 400, seed=2, rare_rows=3)
    _write_synthetic_csv(raw / CICIDS2017_EXPECTED_FILES[6], 400, seed=3)
    return raw


def test_loader_strips_headers_and_drops_identical_duplicate_column(synthetic_raw_dir):
    loader = CICIDS2017Loader(synthetic_raw_dir)
    df = loader.load_merged_dataset()

    assert "Destination Port" in df.columns
    assert all(c == c.strip() for c in df.columns)
    assert "Fwd Header Length.1" not in df.columns  # identical copy removed
    assert "Fwd Header Length" in df.columns
    dropped = [d for item in loader.load_report_["per_file"] for d in item["duplicate_columns_dropped"]]
    assert dropped == ["Fwd Header Length.1"] * 3
    assert len(df) == 3 * 400 + 3 * 5  # every row of every file, duplicates included at this stage


def test_duplicate_columns_with_different_values_are_kept():
    from src.data.loaders import drop_identical_duplicate_columns

    df = pd.DataFrame({"Fwd Header Length": [1, 2], "Fwd Header Length.1": [1, 3]})
    out, dropped, kept_different = drop_identical_duplicate_columns(df)
    assert dropped == []
    assert kept_different == ["Fwd Header Length.1"]
    assert "Fwd Header Length.1" in out.columns


def test_loader_reports_missing_files_without_failing(synthetic_raw_dir):
    loader = CICIDS2017Loader(synthetic_raw_dir)
    loader.load_merged_dataset()
    assert len(loader.find_missing_files()) == len(CICIDS2017_EXPECTED_FILES) - 3
    assert len(loader.load_report_["missing_files"]) == 5


def test_loader_raises_only_when_no_csv_present(tmp_path):
    with pytest.raises(DatasetNotFoundError):
        CICIDS2017Loader(tmp_path).load_merged_dataset()


def test_label_normalization_maps_replacement_character_to_hyphen(synthetic_raw_dir):
    df = CICIDS2017Loader(synthetic_raw_dir).load_merged_dataset()
    X, y_binary, y_multi = CICIDS2017Adapter("Label").extract_labels(df)
    assert "Web Attack - Brute Force" in set(y_multi)
    assert "Label" not in X.columns
    assert set(y_binary.unique()) <= {0, 1}
    assert (y_binary == (y_multi != "BENIGN").astype(int)).all()


def test_audit_counts_missing_infinite_and_duplicate_rows(synthetic_raw_dir):
    df = CICIDS2017Loader(synthetic_raw_dir).load_merged_dataset(add_source_column=True)
    source = df.pop("source_file")
    X, _, y = CICIDS2017Adapter("Label").extract_labels(df)
    result = audit_cicids2017(X, y, source, loader_report=None)
    report = result["report"]

    assert report["n_rows"] == 1215
    assert report["infinite_values"]["total_infinite_cells"] > 0
    assert report["missing_values"]["total_missing_cells"] > 0
    assert report["duplicate_rows_exact_including_label"]["count"] >= 5
    assert report["unexpected_label_values"] == []
    assert set(result["class_composition"].index) == {p.name for p in synthetic_raw_dir.iterdir()}
    assert result["class_distribution"]["count"].sum() == report["n_rows"]


def test_audit_detects_feature_rows_with_conflicting_labels():
    features = pd.DataFrame({"Flow Duration": [1.0, 1.0, 2.0], "Destination Port": [80, 80, 443]})
    labels = pd.Series(["BENIGN", "DoS Hulk", "BENIGN"])
    report = audit_cicids2017(features, labels)["report"]
    assert report["duplicate_feature_rows_with_conflicting_labels"] == {"distinct_feature_vectors": 1, "rows_involved": 2}


def test_identifier_columns_are_dropped_and_leaky_feature_is_flagged():
    rng = np.random.default_rng(0)
    n = 4000
    y = rng.integers(0, 2, size=n)
    X = pd.DataFrame({
        "Flow ID": [f"id{i}" for i in range(n)],
        "Source IP": ["10.0.0.1"] * n,
        "Flow Duration": rng.normal(size=n),
        "target_proxy": y.astype(float),
    })
    X_clean, dropped = drop_identifier_columns(X)
    assert set(dropped) == {"Flow ID", "Source IP"}
    assert list(X_clean.columns) == ["Flow Duration", "target_proxy"]

    scan = single_feature_leakage_scan(X_clean, y, sample_size=None, threshold=0.99)
    flagged = scan.loc[scan["flagged"], "feature"].tolist()
    assert flagged == ["target_proxy"]


def test_preprocessing_statistics_come_from_training_rows_only():
    """The imputation/scaling centre must equal the TRAIN median, not the median over all rows."""
    n = 300
    x = np.arange(n, dtype=float)
    x[200:] += 10_000  # test-like rows far away: full-data median differs noticeably from train median
    y = np.tile([0, 1, 0], n // 3 + 1)[:n]
    X = pd.DataFrame({"feat_a": x, "feat_b": np.sin(np.arange(n))})
    y_multi = pd.Series(np.where(y == 1, "DoS Hulk", "BENIGN"))
    pipe = CyberthreatPreprocessingPipeline(test_size=0.2, val_size=0.1, random_state=42)
    pipe.fit_transform_splits(X, pd.Series(y), y_multi)

    # Recreate exactly the training split the pipeline used (same inputs, same seed).
    X_train_raw, _, _, _ = train_test_split(
        X, pd.Series(y), test_size=pipe.test_size + pipe.val_size, stratify=pd.Series(y), random_state=42
    )
    train_median = X_train_raw["feat_a"].median()
    full_median = X["feat_a"].median()
    assert not np.isclose(train_median, full_median)

    centre = pipe.scaler.scaler_.center_[pipe.scaler.numeric_cols_.index("feat_a")]
    assert np.isclose(centre, train_median)


def test_sample_positions_stratified_cap_keeps_proportions_and_is_reproducible():
    strata = np.array([0] * 900 + [1] * 90 + [2] * 10)
    pos_a, meta = sample_positions(strata, strategy="stratified", max_rows=200, seed=7)
    pos_b, _ = sample_positions(strata, strategy="stratified", max_rows=200, seed=7)
    assert len(pos_a) == 200 and meta["method"] == "stratified_cap"
    assert np.array_equal(pos_a, pos_b)
    kept = np.bincount(strata[pos_a], minlength=3)
    assert kept[2] >= 1  # the rare class is not dropped
    assert abs(kept[0] / 200 - 0.9) < 0.02


def test_sample_positions_none_and_uncapped_keep_every_row():
    strata = np.array([0, 0, 1, 1, 1])
    pos, meta = sample_positions(strata, strategy="none", max_rows=2)
    assert len(pos) == 5 and meta["method"] == "all_rows"
    pos, _ = sample_positions(strata, strategy="stratified", max_rows=None)
    assert len(pos) == 5


def test_sample_positions_falls_back_when_a_class_has_one_member():
    strata = np.array([0] * 50 + [1] * 49 + [2])
    pos, meta = sample_positions(strata, strategy="stratified", max_rows=30, seed=1)
    assert len(pos) == 30 and meta["method"] == "uniform_random_cap"


def test_binary_metrics_match_hand_computed_values():
    y_true = np.array([0, 0, 1, 1])
    y_pred = np.array([0, 1, 1, 1])
    scores = np.array([0.1, 0.6, 0.8, 0.9])
    m = binary_detection_metrics(y_true, y_pred, scores)
    assert m["precision"] == pytest.approx(2 / 3)
    assert m["recall"] == pytest.approx(1.0)
    assert m["f1"] == pytest.approx(0.8)
    assert m["fpr"] == pytest.approx(0.5)
    assert m["roc_auc"] == pytest.approx(1.0)
    assert m["confusion_matrix"]["matrix"] == [[1, 1], [0, 2]]


def test_multiclass_metrics_report_macro_and_per_class_values():
    names = ["BENIGN", "DoS", "PortScan"]
    y_true = np.array([0, 0, 1, 1, 2, 2])
    y_pred = np.array([0, 0, 1, 0, 2, 2])
    proba = np.eye(3)[y_pred] * 0.8 + 0.1
    m = multiclass_metrics(y_true, y_pred, proba, names)
    assert m["accuracy"] == pytest.approx(5 / 6)
    assert m["per_class"]["DoS"]["recall"] == pytest.approx(0.5)
    assert m["per_class"]["DoS"]["precision"] == pytest.approx(1.0)
    assert m["confusion_matrix"]["matrix"][1] == [1, 1, 0]
    assert m["roc_auc_ovr_macro"] is not None


def test_end_to_end_run_on_synthetic_csvs(tmp_path, synthetic_raw_dir):
    """Runs the whole pipeline on synthetic CSVs with tiny models. Outputs go to tmp_path only."""
    cfg = load_config("configs/config.yaml")
    cfg["models"]["baselines"]["random_forest"]["n_estimators"] = 8
    cfg["models"]["advanced"]["xgboost"]["n_estimators"] = 8
    cfg["data"]["cicids2017"]["leakage_scan_rows"] = 500

    summary = run_pipeline(
        cfg,
        raw_dir=str(synthetic_raw_dir),
        results_dir=str(tmp_path / "results"),
        models_dir=str(tmp_path / "models"),
        sampling_strategy="stratified",
        max_train_rows=250,
        data_source=SYNTHETIC_SOURCE,
    )

    assert summary["data_source"] == SYNTHETIC_SOURCE
    assert summary["split_sizes"]["train_used"] == 250
    assert summary["duplicate_rows_removed_before_split"] >= 15  # 5 injected duplicates per file
    assert summary["loader"]["missing_files"]  # only 3 of the 8 expected files were provided
    comparison = pd.read_csv(tmp_path / "results" / "tables" / "cicids2017_model_comparison.csv")
    assert len(comparison) == 4  # 2 tasks x 2 models
    assert set(comparison["model"]) == {"random_forest", "xgboost"}
    assert comparison["accuracy"].between(0, 1).all()

    for task in ("binary", "multiclass"):
        for model in ("random_forest", "xgboost"):
            assert (tmp_path / "results" / "metrics" / f"cicids2017_{task}_{model}.json").exists()
            assert (tmp_path / "models" / f"cicids2017_{task}_{model}.joblib").exists()
    assert (tmp_path / "models" / "cicids2017_preprocessing_pipeline.joblib").exists()
    assert (tmp_path / "results" / "figures" / "cicids2017_binary_roc.png").exists()
    assert (tmp_path / "results" / "reports" / "cicids2017_data_quality_report.json").exists()


def test_saved_detectors_predict_consistently_on_raw_rows(tmp_path, synthetic_raw_dir):
    """Saved artifacts load through CICIDS2017Detector and expose consistent predict/predict_proba."""
    from src.data.dataset_adapters import CICIDS2017Adapter
    from src.models.inference import CICIDS2017Detector

    cfg = load_config("configs/config.yaml")
    cfg["models"]["baselines"]["random_forest"]["n_estimators"] = 8
    cfg["models"]["advanced"]["xgboost"]["n_estimators"] = 8
    models_dir = tmp_path / "models"
    summary = run_pipeline(
        cfg,
        raw_dir=str(synthetic_raw_dir),
        results_dir=str(tmp_path / "results"),
        models_dir=str(models_dir),
        max_train_rows=250,
        data_source=SYNTHETIC_SOURCE,
    )
    raw = CICIDS2017Loader(synthetic_raw_dir).load_merged_dataset()
    X_raw, _, _ = CICIDS2017Adapter("Label").extract_labels(raw)  # raw feature columns, no label

    for task in ("binary", "multiclass"):
        for name in ("random_forest", "xgboost"):
            det = CICIDS2017Detector.load(task, name, artifacts_dir=models_dir)
            proba = det.predict_proba(X_raw.head(50))
            labels = det.predict(X_raw.head(50))
            assert proba.shape == (50, len(det.labels))
            assert np.allclose(proba.sum(axis=1), 1.0, atol=1e-6)
            assert (labels == np.asarray(det.labels)[proba.argmax(axis=1)]).all()

    binary = CICIDS2017Detector.load("binary", "xgboost", artifacts_dir=models_dir)
    assert binary.labels == ["BENIGN", "ATTACK"]
    multi = CICIDS2017Detector.load("multiclass", "random_forest", artifacts_dir=models_dir)
    assert multi.labels == summary["class_names"]
    with pytest.raises(ValueError, match="missing"):
        binary.predict(X_raw.drop(columns=[X_raw.columns[0]]))


def test_cap_per_class_keeps_all_rare_rows_and_caps_dominant_classes():
    from src.preprocessing.sampling import cap_per_class_positions

    strata = np.array([0] * 1000 + [1] * 50 + [2] * 3)
    pos = cap_per_class_positions(strata, max_per_class=100, seed=1)
    kept = np.bincount(strata[pos], minlength=3)
    assert kept.tolist() == [100, 50, 3]
    assert np.array_equal(pos, cap_per_class_positions(strata, max_per_class=100, seed=1))
